apiVersion: v1
kind: Service
metadata:
  name: smart-contract-service
  namespace: smart-contract
spec:
  selector:
    app: smart-contract
  ports:
    - protocol: TCP
      port: 8545
      targetPort: 8545
  type: LoadBalancer
